/**
 * Complete list of chartered cities in the Philippines.
 * Includes all Highly Urbanized Cities (HUCs), Independent Component Cities,
 * and Component Cities across all regions (including NCR, CAR, BARMM).
 *
 * Disambiguated names are used where two cities share the same name
 * (e.g. San Carlos, Naga, Talisay, San Fernando).
 */
export const PH_CITIES: readonly string[] = [
  "Alaminos",
  "Angeles",
  "Antipolo",
  "Bacoor",
  "Baguio",
  "Bacolod",
  "Balanga",
  "Batac",
  "Batangas City",
  "Bayugan",
  "Baybay",
  "Biñan",
  "Bislig",
  "Bogo",
  "Borongan",
  "Butuan",
  "Cabadbaran",
  "Cabanatuan",
  "Cabuyao",
  "Cadiz",
  "Cagayan de Oro",
  "Calapan",
  "Calamba",
  "Calbayog",
  "Caloocan",
  "Candon",
  "Carcar",
  "Catbalogan",
  "Cauayan",
  "Cavite City",
  "Cebu City",
  "Cotabato City",
  "Dagupan",
  "Danao",
  "Dapitan",
  "Dasmariñas",
  "Davao City",
  "Digos",
  "Dipolog",
  "El Salvador",
  "Escalante",
  "Gapan",
  "General Santos",
  "General Trias",
  "Gingoog",
  "Himamaylan",
  "Ilagan",
  "Iligan",
  "Iloilo City",
  "Imus",
  "Iriga",
  "Isabela City",
  "Island Garden City of Samal",
  "Kabankalan",
  "Kidapawan",
  "Koronadal",
  "La Carlota",
  "Lamitan",
  "Lapu-Lapu",
  "Las Piñas",
  "Legazpi",
  "Ligao",
  "Lipa",
  "Laoag",
  "Lucena",
  "Maasin",
  "Makati",
  "Malabon",
  "Malaybalay",
  "Malolos",
  "Mandaue",
  "Mandaluyong",
  "Manila",
  "Marawi",
  "Marikina",
  "Masbate City",
  "Mati",
  "Meycauayan",
  "Muñoz",
  "Muntinlupa",
  "Naga (Camarines Sur)",
  "Naga (Cebu)",
  "Navotas",
  "Olongapo",
  "Ormoc",
  "Oroquieta",
  "Ozamiz",
  "Pagadian",
  "Palayan",
  "Panabo",
  "Parañaque",
  "Pasay",
  "Pasig",
  "Puerto Princesa",
  "Quezon City",
  "Roxas City",
  "Sagay",
  "San Carlos (Negros Occidental)",
  "San Carlos (Pangasinan)",
  "San Fernando (La Union)",
  "San Fernando (Pampanga)",
  "San Jose del Monte",
  "San Juan",
  "San Pablo",
  "San Pedro",
  "Santa Rosa",
  "Santiago",
  "Silay",
  "Sipalay",
  "Sorsogon City",
  "Surigao City",
  "Tabaco",
  "Tabuk",
  "Tacloban",
  "Tacurong",
  "Tagaytay",
  "Tagbilaran",
  "Taguig",
  "Tagum",
  "Talisay (Cebu)",
  "Talisay (Negros Occidental)",
  "Tanauan",
  "Tangub",
  "Tarlac City",
  "Tayabas",
  "Toledo",
  "Trece Martires",
  "Tuguegarao",
  "Urdaneta",
  "Valencia",
  "Valenzuela",
  "Victorias",
  "Vigan",
  "Zamboanga City",
].sort((a, b) => a.localeCompare(b, "en-PH"));
